<?php
include 'header.phtml';
?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Agregar Categoría</title>
</head>
<body>
    <h1>Agregar Categoría</h1>
    <form method="POST">
        <label>Nombre:</label>
        <input type="text" name="nombre" required>
        <button type="submit">Agregar</button>
    </form>
    <a href="<?php echo BASE_URL; ?>visor-categorias">Volver a la lista de categorías</a>
</body>
</html>
<?php
include 'footer.phtml';
?>