<?php include 'header.phtml'; // Incluir el header ?>
<body>
    <h1>Estas en Modo Administrador!</h1>
    <h2>Gestion de Items</h2>
    <ul>
        <li><a href="<?php echo BASE_URL; ?>listar-item">Gestionar Items</a></li>
    </ul>
    <h2>Gestion de Categorias</h2>
    <ul>
        <li><a href="<?php echo BASE_URL; ?>visor-categorias">Gestionar Categorías</a></li>
    </ul>
<?php include 'footer.phtml'; // Incluir el footer ?>
