<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>iConnect - Inicio de Sesion</title>
    <style>
        .alert {
            color: red;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="login-content">
    <form method="POST">
    <h2 class="title">Iniciar Sesión</h2>
    <?php
    if (!empty($_POST["ingresar"])) {
        if (empty($_POST["usuario"]) || empty($_POST["password"])) {
            echo "<div class='alert'>Los campos están vacíos</div>";
        } else {
            $usuario = $_POST["usuario"];
            $password = $_POST["password"];
            
            $conexion = new PDO('mysql:host=localhost;dbname=db_iconnect;charset=utf8', 'root', '');
            $sql = $conexion->prepare("SELECT * FROM usuarios WHERE usuario = ? AND password = ?");
            $sql->execute([$usuario, $password]);
            $datos = $sql->fetch(PDO::FETCH_OBJ);

            // Verificar si se encontró un usuario y la contraseña son correctos
            if ($datos) {
                // Almacenar información del usuario en la sesión
                $_SESSION['usuario'] = $usuario; // o cualquier otra información relevante
                header("location: dashboard");
                exit();
            } else {
                echo "<div class='alert'><h1>ACCESO DENEGADO</h1></div>";
            }
        }
    }
    ?>
    <div class="input-usuario">
        <label for="usuario">Usuario:</label>
        <input type="text" name="usuario">
    </div>

    <div class="input-password">
        <label for="contraseña">Contraseña:</label>
        <input type="password" name="password">
    </div>

    <div class="btn-login">
        <input name="ingresar" type="submit" value="Iniciar Sesión">
    </div>
</form>
    </div>
</body>
</html>
